version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  
  kafka:
    image: bitnami/kafka:latest
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://<your-ec2-public-ip>:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  
  ingestion:
    build:
      context: ./ingestion
    volumes:
      - ./ingestion:/app
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092  # Link to kafka service
      - KAFKA_TOPIC=crypto-prices
      - COINGECKO_API=https://api.coingecko.com/api/v3/simple/price
      - COINS=bitcoin,ethereum  # Expand to 50 coins as needed
    depends_on:
      - kafka