services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  
  kafka:
    image: bitnami/kafka:latest
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://172-31-23-60:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  
  ingestion:
    build:
      context: .
    volumes:
      - ./:/app
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=crypto-prices
      - COINGECKO_API=https://api.coingecko.com/api/v3/simple/price
      - COINS=bitcoin,ethereum,binancecoin,tether,solana,ripple,cardano,dogecoin,tron,avalanche-2,chainlink,polkadot,polygon,litecoin,near,uniswap,cosmos,stellar,algorand,vechain,internet-computer,filecoin,aptos,hedera,arbitrum
    depends_on:
      - kafka